### ISSUE TITLE
How do you perform model selection?

### ISSUE THREAD

**Issue by xiabingquan** [Sally-SH/VSP-LLM#2]
Thanks for the great work.

After thoroughly readinging your codes, I'm wondering how you perform model selection. 
Did you perform model average on the several last checkpoints? Or did you evaluate each checkpoint on the validation set and them average the several best checkpoints? 

I did not find any clue in the codes. Any reply will be appreciated, thanks!

**Comment by Sally-SH** [comment]
We selected the checkpoint that achieved the highest accuracy on the validation set.
Thank you for your question.
